name: Run AI Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24' 
      - run: npm install
      - run: npm install @google/generative-ai@latest
      - run: npm start
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
